version: '3.8'

services:

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api4
    ports:
      - "5001:5001"
    env_file:
    - ./server/.env
    restart: always

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui4
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: always